# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Node version, install dependencies and run tests with NPM
# For more information see: https://github.com/actions/setup-node

name: Node

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
    # To automatically get bug fixes and new Node versions for node/setup-node,
    # change this to (see https://github.com/actions/setup-node#versioning):
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install
    - run: yarn test


